version: '3'

services:
  gobarber_dev:
    image: postgres
    container_name: gobarber_dev
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gobarber_dev
    volumes:
      - pg:/data/postgres

volumes:
  pg:
    driver: local
